exclude: '^(doc)|(cookiecutters)'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: trailing-whitespace
    exclude: (example)
  - id: end-of-file-fixer
    exclude: (example)
  - id: check-yaml
    exclude: (example)
    args: ['--unsafe']
  - id: check-json
    exclude: (example)
  - id: check-added-large-files
    exclude: (example|tests/test_data/PROCAR.mgo)
  - id: double-quote-string-fixer
    exclude: (example)
  - id: forbid-new-submodules
    exclude: (example)

- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.30.0
  hooks:
  - id: yapf
    name: yapf
    types: [python]
    args: ['-i']
    exclude: (example)


- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    types: [python]
    language: system
    exclude: |
      (?x)(
      ^tutorials/|
      ^examples/|
      ^tests
      )
