site_name: easyunfold Docs
theme:
  name: material
  icon:
    repo:  fontawesome/brands/github
  palette:
    primary: purple

nav:
  - Home: "index.md"
  - Installation: "installation.md"
  - Guide: "guide.md"
  - CLI Commands: "cli.md"
  - API Docs:
      "easyunfold.effective_mass": "sources/modules/easyunfold/effective_mass.md"
      "easyunfold.plotting": "sources/modules/easyunfold/plotting.md"
      "easyunfold.procar": "sources/modules/easyunfold/procar.md"
      "easyunfold.unfold": "sources/modules/easyunfold/unfold.md"
      "easyunfold.wavecar": "sources/modules/easyunfold/wavecar.md"

  - Theory: "theory.md"
  - Examples:
      "Si Supercell": "example_si222.md"
      "MgO Projection": "example_mgo.md"
      "NaBiS2 SQS Projection": "example_nabis2.md"

markdown_extensions:
  - attr_list
  - mkdocs-click
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://github.com/SMTG-UCL/easyunfold
